name: devhyeon_tools
description: "DevHyeon Tools Flutter Project"
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  intl: any
  flutter_syntax_view: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/