name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.4'
          channel: 'stable'
      - run: flutter --version
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        # 1. change path which exist lib/main.dart
        working-directory: ./Users/devhyeon_github/devhyeon_tools
      - run: |
          cd build/web
          git init
          git config --global user.email devhyeon0312@gmail.com
          git config --global user.name 양영현
          git status
          git remote add origin https://$@github.com/DevHyeon0312/devhyeon_tools.git 
          git checkout -b web-pages
          git add --all
          git commit -m "update"
          git push origin web-pages -f